language: r
warnings_are_errors: true
sudo: required

r_packages:
  - covr
  
after_success:
  - Rscript -e "library(covr); codecov()"

notifications:
  email:
    on_success: change
    on_failure: change
